### PR TITLE
Ensure that bravado.client.SwaggerSpec is deep copyable

### PR DESCRIPTION
**Pull request by macisamuele**
The goal of this PR is similar to https://github.com/Yelp/bravado-core/pull/360.

It ensures that a `bravado.client.SwaggerSpec` is deep copyable.

In order to achieve it we need to make sure that bravado-core>=5.16.0 is in use (at it is the first version that does allow deepcopy of `Spec` instances).

The equality methods on `RequestsClient`, `FidoClient` and `SwaggerClient` have been defined mostly to have ensure that we can run `client == deepcopy(client)`

### CODE REVIEW

**Comment by sjaensch** [comment]
@macisamuele the build is failing for this branch, not sure if you have seen it.

**Comment by macisamuele** [comment]
@sjaensch I've seen the red build ... unfortunately lack of bandwidth made me postpone this.
I'll try to get back ASAP

**Comment by macisamuele** [comment]
FTY: @sjaensch 

I've dug a bit more into the test failures in Python 3.5.0 and I did found out that the issue is a known issue for the CPython implementation ([issue link](https://bugs.python.org/issue25447)) and that it has already been resolved.

My proposal at this point would be to:
 * skip the test case in case of Python 3.5.0
 * update the bravado-core changelog highlighting the fact that deepcopy might not work properly on CPython 3.5.0 (tests are failing there as well, [travis](https://travis-ci.org/macisamuele/bravado-core)) 

---

Details of test run (done via docker)
```
(py35) root@fc956c1ae6b5:/code# python -m pytest --pdbcls=IPython.terminal.debugger:TerminalPdb --pdb tests/spec/Spec/deepcopy_test.py
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.5.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /code, inifile: tox.ini
plugins: cov-2.8.1, benchmark-3.2.2
collected 1 item

tests/spec/Spec/deepcopy_test.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

petstore_spec = <bravado_core.spec.Spec object at 0x7f4f574ed978>

    def test_spec_instance_is_deep_copyable(petstore_spec):
>       check_object_deepcopy(petstore_spec)

tests/spec/Spec/deepcopy_test.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/conftest.py:285: in check_object_deepcopy
    obj_copy = deepcopy(obj)
.tox/py35/lib/python3.5/copy.py:166: in deepcopy
    y = copier(memo)
bravado_core/spec.py:181: in __deepcopy__
    setattr(copied_self, attr_name, deepcopy(attr_value, memo=memo))
.tox/py35/lib/python3.5/copy.py:182: in deepcopy
    y = _reconstruct(x, rv, 1, memo)
.tox/py35/lib/python3.5/copy.py:298: in _reconstruct
    state = deepcopy(state, memo)
.tox/py35/lib/python3.5/copy.py:155: in deepcopy
    y = copier(x, memo)
.tox/py35/lib/python3.5/copy.py:244: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
.tox/py35/lib/python3.5/copy.py:182: in deepcopy
    y = _reconstruct(x, rv, 1, memo)
.tox/py35/lib/python3.5/copy.py:293: in _reconstruct
    y = callable(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'functools._lru_cache_wrapper'>, args = ()

    def __newobj__(cls, *args):
>       return cls.__new__(cls, *args)
E       TypeError: Required argument 'user_function' (pos 1) not found

.tox/py35/lib/python3.5/copyreg.py:88: TypeError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /code/.tox/py35/lib/python3.5/copyreg.py(88)__newobj__()
     86
     87 def __newobj__(cls, *args):
---> 88     return cls.__new__(cls, *args)
     89
     90 def __newobj_ex__(cls, args, kwargs):

ipdb> args
cls = <class 'functools._lru_cache_wrapper'>
args = ()
```

**Comment by sjaensch** [comment]
Sounds good to me @macisamuele! I'd also be fine with dropping support for Python 3.5.0 altogether.

**Comment by macisamuele** [comment]
As bravado-core==5.16.1 has been released we can move forward with this PR.

I'm going to:
 * drop support for python 3.5.0 (and previous python 3 versions)
 * replace  `SwaggerClient.__eq__` method with `SwaggerClient.is_equal`  in order to avoid compromising hashability of the `SwaggerClient` (check https://github.com/Yelp/bravado-core/pull/364 for additional context)

**Pull request merged**
