### PR TITLE
msgpack-python is deprecated. Use msgpack instead.

### PR DESCRIPTION
**Pull request by ecederstrand**
See https://pypi.org/project/msgpack-python/

### CODE REVIEW

**Comment by ecederstrand** [comment]
@sjaensch Is this change something Bravado is interested in?

**Comment by sjaensch** [comment]
Hey @ecederstrand, thank you for your contribution and sorry for the delay! Going to merge this in.

**Comment by ecederstrand** [comment]
No problem, and thanks!

**Comment by sjaensch** [comment]
This change has been released in the 10.6.3 version of bravado.

**Pull request merged**
